// Code generated by protoc-gen-go. DO NOT EDIT.
// source: remoteid/remoteid.proto

package remoteid // import "github.com/airmap/interfaces/src/go/remoteid"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import geo "github.com/airmap/interfaces/src/go/geo"
import ids "github.com/airmap/interfaces/src/go/ids"
import measurements "github.com/airmap/interfaces/src/go/measurements"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Aircraft_Type int32

const (
	Aircraft_UNKNOWN                Aircraft_Type = 0
	Aircraft_AIRPLANE               Aircraft_Type = 1
	Aircraft_ROTORCRAFT             Aircraft_Type = 2
	Aircraft_GYROPLANE              Aircraft_Type = 3
	Aircraft_VTOL                   Aircraft_Type = 4
	Aircraft_ORNITHOPTER            Aircraft_Type = 5
	Aircraft_GLIDER                 Aircraft_Type = 6
	Aircraft_KITE                   Aircraft_Type = 7
	Aircraft_FREE_BALOON            Aircraft_Type = 8
	Aircraft_CAPTIVE_BALLOON        Aircraft_Type = 9
	Aircraft_AIRSHIP                Aircraft_Type = 10
	Aircraft_FREE_FALL_OR_PARACHUTE Aircraft_Type = 11
	Aircraft_ROCKET                 Aircraft_Type = 12
	Aircraft_GROUND_OBSTACLE        Aircraft_Type = 13
	Aircraft_OTHER                  Aircraft_Type = 14
)

var Aircraft_Type_name = map[int32]string{
	0:  "UNKNOWN",
	1:  "AIRPLANE",
	2:  "ROTORCRAFT",
	3:  "GYROPLANE",
	4:  "VTOL",
	5:  "ORNITHOPTER",
	6:  "GLIDER",
	7:  "KITE",
	8:  "FREE_BALOON",
	9:  "CAPTIVE_BALLOON",
	10: "AIRSHIP",
	11: "FREE_FALL_OR_PARACHUTE",
	12: "ROCKET",
	13: "GROUND_OBSTACLE",
	14: "OTHER",
}
var Aircraft_Type_value = map[string]int32{
	"UNKNOWN":                0,
	"AIRPLANE":               1,
	"ROTORCRAFT":             2,
	"GYROPLANE":              3,
	"VTOL":                   4,
	"ORNITHOPTER":            5,
	"GLIDER":                 6,
	"KITE":                   7,
	"FREE_BALOON":            8,
	"CAPTIVE_BALLOON":        9,
	"AIRSHIP":                10,
	"FREE_FALL_OR_PARACHUTE": 11,
	"ROCKET":                 12,
	"GROUND_OBSTACLE":        13,
	"OTHER":                  14,
}

func (x Aircraft_Type) String() string {
	return proto.EnumName(Aircraft_Type_name, int32(x))
}
func (Aircraft_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_remoteid_2e8f532f1597596d, []int{4, 0}
}

// MonitorAreaParameters bundles parameters used in the MonitorOperationsArea rpc.
type MonitorAreaParameters struct {
	AreaOfInterest       *geo.BoundingBox `protobuf:"bytes,1,opt,name=area_of_interest,json=areaOfInterest,proto3" json:"area_of_interest,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *MonitorAreaParameters) Reset()         { *m = MonitorAreaParameters{} }
func (m *MonitorAreaParameters) String() string { return proto.CompactTextString(m) }
func (*MonitorAreaParameters) ProtoMessage()    {}
func (*MonitorAreaParameters) Descriptor() ([]byte, []int) {
	return fileDescriptor_remoteid_2e8f532f1597596d, []int{0}
}
func (m *MonitorAreaParameters) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MonitorAreaParameters.Unmarshal(m, b)
}
func (m *MonitorAreaParameters) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MonitorAreaParameters.Marshal(b, m, deterministic)
}
func (dst *MonitorAreaParameters) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MonitorAreaParameters.Merge(dst, src)
}
func (m *MonitorAreaParameters) XXX_Size() int {
	return xxx_messageInfo_MonitorAreaParameters.Size(m)
}
func (m *MonitorAreaParameters) XXX_DiscardUnknown() {
	xxx_messageInfo_MonitorAreaParameters.DiscardUnknown(m)
}

var xxx_messageInfo_MonitorAreaParameters proto.InternalMessageInfo

func (m *MonitorAreaParameters) GetAreaOfInterest() *geo.BoundingBox {
	if m != nil {
		return m.AreaOfInterest
	}
	return nil
}

type MonitorAreaResponse struct {
	// details is a discriminated union of response types
	//
	// Types that are valid to be assigned to Details:
	//	*MonitorAreaResponse_Added_
	//	*MonitorAreaResponse_Updated_
	//	*MonitorAreaResponse_Removed_
	Details              isMonitorAreaResponse_Details `protobuf_oneof:"details"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *MonitorAreaResponse) Reset()         { *m = MonitorAreaResponse{} }
func (m *MonitorAreaResponse) String() string { return proto.CompactTextString(m) }
func (*MonitorAreaResponse) ProtoMessage()    {}
func (*MonitorAreaResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_remoteid_2e8f532f1597596d, []int{1}
}
func (m *MonitorAreaResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MonitorAreaResponse.Unmarshal(m, b)
}
func (m *MonitorAreaResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MonitorAreaResponse.Marshal(b, m, deterministic)
}
func (dst *MonitorAreaResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MonitorAreaResponse.Merge(dst, src)
}
func (m *MonitorAreaResponse) XXX_Size() int {
	return xxx_messageInfo_MonitorAreaResponse.Size(m)
}
func (m *MonitorAreaResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MonitorAreaResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MonitorAreaResponse proto.InternalMessageInfo

type isMonitorAreaResponse_Details interface {
	isMonitorAreaResponse_Details()
}

type MonitorAreaResponse_Added_ struct {
	Added *MonitorAreaResponse_Added `protobuf:"bytes,1,opt,name=added,proto3,oneof"`
}

type MonitorAreaResponse_Updated_ struct {
	Updated *MonitorAreaResponse_Updated `protobuf:"bytes,2,opt,name=updated,proto3,oneof"`
}

type MonitorAreaResponse_Removed_ struct {
	Removed *MonitorAreaResponse_Removed `protobuf:"bytes,3,opt,name=removed,proto3,oneof"`
}

func (*MonitorAreaResponse_Added_) isMonitorAreaResponse_Details() {}

func (*MonitorAreaResponse_Updated_) isMonitorAreaResponse_Details() {}

func (*MonitorAreaResponse_Removed_) isMonitorAreaResponse_Details() {}

func (m *MonitorAreaResponse) GetDetails() isMonitorAreaResponse_Details {
	if m != nil {
		return m.Details
	}
	return nil
}

func (m *MonitorAreaResponse) GetAdded() *MonitorAreaResponse_Added {
	if x, ok := m.GetDetails().(*MonitorAreaResponse_Added_); ok {
		return x.Added
	}
	return nil
}

func (m *MonitorAreaResponse) GetUpdated() *MonitorAreaResponse_Updated {
	if x, ok := m.GetDetails().(*MonitorAreaResponse_Updated_); ok {
		return x.Updated
	}
	return nil
}

func (m *MonitorAreaResponse) GetRemoved() *MonitorAreaResponse_Removed {
	if x, ok := m.GetDetails().(*MonitorAreaResponse_Removed_); ok {
		return x.Removed
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*MonitorAreaResponse) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _MonitorAreaResponse_OneofMarshaler, _MonitorAreaResponse_OneofUnmarshaler, _MonitorAreaResponse_OneofSizer, []interface{}{
		(*MonitorAreaResponse_Added_)(nil),
		(*MonitorAreaResponse_Updated_)(nil),
		(*MonitorAreaResponse_Removed_)(nil),
	}
}

func _MonitorAreaResponse_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*MonitorAreaResponse)
	// details
	switch x := m.Details.(type) {
	case *MonitorAreaResponse_Added_:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Added); err != nil {
			return err
		}
	case *MonitorAreaResponse_Updated_:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Updated); err != nil {
			return err
		}
	case *MonitorAreaResponse_Removed_:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Removed); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("MonitorAreaResponse.Details has unexpected type %T", x)
	}
	return nil
}

func _MonitorAreaResponse_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*MonitorAreaResponse)
	switch tag {
	case 1: // details.added
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(MonitorAreaResponse_Added)
		err := b.DecodeMessage(msg)
		m.Details = &MonitorAreaResponse_Added_{msg}
		return true, err
	case 2: // details.updated
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(MonitorAreaResponse_Updated)
		err := b.DecodeMessage(msg)
		m.Details = &MonitorAreaResponse_Updated_{msg}
		return true, err
	case 3: // details.removed
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(MonitorAreaResponse_Removed)
		err := b.DecodeMessage(msg)
		m.Details = &MonitorAreaResponse_Removed_{msg}
		return true, err
	default:
		return false, nil
	}
}

func _MonitorAreaResponse_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*MonitorAreaResponse)
	// details
	switch x := m.Details.(type) {
	case *MonitorAreaResponse_Added_:
		s := proto.Size(x.Added)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *MonitorAreaResponse_Updated_:
		s := proto.Size(x.Updated)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *MonitorAreaResponse_Removed_:
		s := proto.Size(x.Removed)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

// Added models an operation that has entered the monitored area.
type MonitorAreaResponse_Added struct {
	Operation            *Operation        `protobuf:"bytes,1,opt,name=operation,proto3" json:"operation,omitempty"`
	Positions            []*geo.Position4D `protobuf:"bytes,2,rep,name=positions,proto3" json:"positions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *MonitorAreaResponse_Added) Reset()         { *m = MonitorAreaResponse_Added{} }
func (m *MonitorAreaResponse_Added) String() string { return proto.CompactTextString(m) }
func (*MonitorAreaResponse_Added) ProtoMessage()    {}
func (*MonitorAreaResponse_Added) Descriptor() ([]byte, []int) {
	return fileDescriptor_remoteid_2e8f532f1597596d, []int{1, 0}
}
func (m *MonitorAreaResponse_Added) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MonitorAreaResponse_Added.Unmarshal(m, b)
}
func (m *MonitorAreaResponse_Added) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MonitorAreaResponse_Added.Marshal(b, m, deterministic)
}
func (dst *MonitorAreaResponse_Added) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MonitorAreaResponse_Added.Merge(dst, src)
}
func (m *MonitorAreaResponse_Added) XXX_Size() int {
	return xxx_messageInfo_MonitorAreaResponse_Added.Size(m)
}
func (m *MonitorAreaResponse_Added) XXX_DiscardUnknown() {
	xxx_messageInfo_MonitorAreaResponse_Added.DiscardUnknown(m)
}

var xxx_messageInfo_MonitorAreaResponse_Added proto.InternalMessageInfo

func (m *MonitorAreaResponse_Added) GetOperation() *Operation {
	if m != nil {
		return m.Operation
	}
	return nil
}

func (m *MonitorAreaResponse_Added) GetPositions() []*geo.Position4D {
	if m != nil {
		return m.Positions
	}
	return nil
}

// Updated models an operation that has been updated in the monitored area.
type MonitorAreaResponse_Updated struct {
	// details is a discriminated union of update types
	//
	// Types that are valid to be assigned to Details:
	//	*MonitorAreaResponse_Updated_Operation
	//	*MonitorAreaResponse_Updated_State
	Details              isMonitorAreaResponse_Updated_Details `protobuf_oneof:"details"`
	XXX_NoUnkeyedLiteral struct{}                              `json:"-"`
	XXX_unrecognized     []byte                                `json:"-"`
	XXX_sizecache        int32                                 `json:"-"`
}

func (m *MonitorAreaResponse_Updated) Reset()         { *m = MonitorAreaResponse_Updated{} }
func (m *MonitorAreaResponse_Updated) String() string { return proto.CompactTextString(m) }
func (*MonitorAreaResponse_Updated) ProtoMessage()    {}
func (*MonitorAreaResponse_Updated) Descriptor() ([]byte, []int) {
	return fileDescriptor_remoteid_2e8f532f1597596d, []int{1, 1}
}
func (m *MonitorAreaResponse_Updated) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MonitorAreaResponse_Updated.Unmarshal(m, b)
}
func (m *MonitorAreaResponse_Updated) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MonitorAreaResponse_Updated.Marshal(b, m, deterministic)
}
func (dst *MonitorAreaResponse_Updated) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MonitorAreaResponse_Updated.Merge(dst, src)
}
func (m *MonitorAreaResponse_Updated) XXX_Size() int {
	return xxx_messageInfo_MonitorAreaResponse_Updated.Size(m)
}
func (m *MonitorAreaResponse_Updated) XXX_DiscardUnknown() {
	xxx_messageInfo_MonitorAreaResponse_Updated.DiscardUnknown(m)
}

var xxx_messageInfo_MonitorAreaResponse_Updated proto.InternalMessageInfo

type isMonitorAreaResponse_Updated_Details interface {
	isMonitorAreaResponse_Updated_Details()
}

type MonitorAreaResponse_Updated_Operation struct {
	Operation *Operation `protobuf:"bytes,1,opt,name=operation,proto3,oneof"`
}

type MonitorAreaResponse_Updated_State struct {
	State *Operation_State `protobuf:"bytes,2,opt,name=state,proto3,oneof"`
}

func (*MonitorAreaResponse_Updated_Operation) isMonitorAreaResponse_Updated_Details() {}

func (*MonitorAreaResponse_Updated_State) isMonitorAreaResponse_Updated_Details() {}

func (m *MonitorAreaResponse_Updated) GetDetails() isMonitorAreaResponse_Updated_Details {
	if m != nil {
		return m.Details
	}
	return nil
}

func (m *MonitorAreaResponse_Updated) GetOperation() *Operation {
	if x, ok := m.GetDetails().(*MonitorAreaResponse_Updated_Operation); ok {
		return x.Operation
	}
	return nil
}

func (m *MonitorAreaResponse_Updated) GetState() *Operation_State {
	if x, ok := m.GetDetails().(*MonitorAreaResponse_Updated_State); ok {
		return x.State
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*MonitorAreaResponse_Updated) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _MonitorAreaResponse_Updated_OneofMarshaler, _MonitorAreaResponse_Updated_OneofUnmarshaler, _MonitorAreaResponse_Updated_OneofSizer, []interface{}{
		(*MonitorAreaResponse_Updated_Operation)(nil),
		(*MonitorAreaResponse_Updated_State)(nil),
	}
}

func _MonitorAreaResponse_Updated_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*MonitorAreaResponse_Updated)
	// details
	switch x := m.Details.(type) {
	case *MonitorAreaResponse_Updated_Operation:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Operation); err != nil {
			return err
		}
	case *MonitorAreaResponse_Updated_State:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.State); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("MonitorAreaResponse_Updated.Details has unexpected type %T", x)
	}
	return nil
}

func _MonitorAreaResponse_Updated_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*MonitorAreaResponse_Updated)
	switch tag {
	case 1: // details.operation
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Operation)
		err := b.DecodeMessage(msg)
		m.Details = &MonitorAreaResponse_Updated_Operation{msg}
		return true, err
	case 2: // details.state
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Operation_State)
		err := b.DecodeMessage(msg)
		m.Details = &MonitorAreaResponse_Updated_State{msg}
		return true, err
	default:
		return false, nil
	}
}

func _MonitorAreaResponse_Updated_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*MonitorAreaResponse_Updated)
	// details
	switch x := m.Details.(type) {
	case *MonitorAreaResponse_Updated_Operation:
		s := proto.Size(x.Operation)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *MonitorAreaResponse_Updated_State:
		s := proto.Size(x.State)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

// Removed models an operation that has been removed from the monitored area.
type MonitorAreaResponse_Removed struct {
	Id                   *ids.Operation `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *MonitorAreaResponse_Removed) Reset()         { *m = MonitorAreaResponse_Removed{} }
func (m *MonitorAreaResponse_Removed) String() string { return proto.CompactTextString(m) }
func (*MonitorAreaResponse_Removed) ProtoMessage()    {}
func (*MonitorAreaResponse_Removed) Descriptor() ([]byte, []int) {
	return fileDescriptor_remoteid_2e8f532f1597596d, []int{1, 2}
}
func (m *MonitorAreaResponse_Removed) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MonitorAreaResponse_Removed.Unmarshal(m, b)
}
func (m *MonitorAreaResponse_Removed) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MonitorAreaResponse_Removed.Marshal(b, m, deterministic)
}
func (dst *MonitorAreaResponse_Removed) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MonitorAreaResponse_Removed.Merge(dst, src)
}
func (m *MonitorAreaResponse_Removed) XXX_Size() int {
	return xxx_messageInfo_MonitorAreaResponse_Removed.Size(m)
}
func (m *MonitorAreaResponse_Removed) XXX_DiscardUnknown() {
	xxx_messageInfo_MonitorAreaResponse_Removed.DiscardUnknown(m)
}

var xxx_messageInfo_MonitorAreaResponse_Removed proto.InternalMessageInfo

func (m *MonitorAreaResponse_Removed) GetId() *ids.Operation {
	if m != nil {
		return m.Id
	}
	return nil
}

// Operation models an aerial operation in a given area.
type Operation struct {
	Id                   *ids.Operation `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Operator             *Operator      `protobuf:"bytes,2,opt,name=operator,proto3" json:"operator,omitempty"`
	Aircraft             *Aircraft      `protobuf:"bytes,3,opt,name=aircraft,proto3" json:"aircraft,omitempty"`
	Geometry             *geo.Polygon   `protobuf:"bytes,4,opt,name=geometry,proto3" json:"geometry,omitempty"`
	Purpose              string         `protobuf:"bytes,5,opt,name=purpose,proto3" json:"purpose,omitempty"`
	Simulated            bool           `protobuf:"varint,6,opt,name=simulated,proto3" json:"simulated,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Operation) Reset()         { *m = Operation{} }
func (m *Operation) String() string { return proto.CompactTextString(m) }
func (*Operation) ProtoMessage()    {}
func (*Operation) Descriptor() ([]byte, []int) {
	return fileDescriptor_remoteid_2e8f532f1597596d, []int{2}
}
func (m *Operation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Operation.Unmarshal(m, b)
}
func (m *Operation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Operation.Marshal(b, m, deterministic)
}
func (dst *Operation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Operation.Merge(dst, src)
}
func (m *Operation) XXX_Size() int {
	return xxx_messageInfo_Operation.Size(m)
}
func (m *Operation) XXX_DiscardUnknown() {
	xxx_messageInfo_Operation.DiscardUnknown(m)
}

var xxx_messageInfo_Operation proto.InternalMessageInfo

func (m *Operation) GetId() *ids.Operation {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *Operation) GetOperator() *Operator {
	if m != nil {
		return m.Operator
	}
	return nil
}

func (m *Operation) GetAircraft() *Aircraft {
	if m != nil {
		return m.Aircraft
	}
	return nil
}

func (m *Operation) GetGeometry() *geo.Polygon {
	if m != nil {
		return m.Geometry
	}
	return nil
}

func (m *Operation) GetPurpose() string {
	if m != nil {
		return m.Purpose
	}
	return ""
}

func (m *Operation) GetSimulated() bool {
	if m != nil {
		return m.Simulated
	}
	return false
}

// State models an operation's current state
type Operation_State struct {
	Id                   *ids.Operation                  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Timestamp            *timestamp.Timestamp            `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Position             *measurements.Position_Absolute `protobuf:"bytes,3,opt,name=position,proto3" json:"position,omitempty"`
	Velocity             *measurements.Velocity_Polar    `protobuf:"bytes,4,opt,name=velocity,proto3" json:"velocity,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                        `json:"-"`
	XXX_unrecognized     []byte                          `json:"-"`
	XXX_sizecache        int32                           `json:"-"`
}

func (m *Operation_State) Reset()         { *m = Operation_State{} }
func (m *Operation_State) String() string { return proto.CompactTextString(m) }
func (*Operation_State) ProtoMessage()    {}
func (*Operation_State) Descriptor() ([]byte, []int) {
	return fileDescriptor_remoteid_2e8f532f1597596d, []int{2, 0}
}
func (m *Operation_State) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Operation_State.Unmarshal(m, b)
}
func (m *Operation_State) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Operation_State.Marshal(b, m, deterministic)
}
func (dst *Operation_State) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Operation_State.Merge(dst, src)
}
func (m *Operation_State) XXX_Size() int {
	return xxx_messageInfo_Operation_State.Size(m)
}
func (m *Operation_State) XXX_DiscardUnknown() {
	xxx_messageInfo_Operation_State.DiscardUnknown(m)
}

var xxx_messageInfo_Operation_State proto.InternalMessageInfo

func (m *Operation_State) GetId() *ids.Operation {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *Operation_State) GetTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func (m *Operation_State) GetPosition() *measurements.Position_Absolute {
	if m != nil {
		return m.Position
	}
	return nil
}

func (m *Operation_State) GetVelocity() *measurements.Velocity_Polar {
	if m != nil {
		return m.Velocity
	}
	return nil
}

// Operator models the operator of an aircraft
type Operator struct {
	Id                   *ids.Operator     `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Location             *geo.Coordinate2D `protobuf:"bytes,2,opt,name=location,proto3" json:"location,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Operator) Reset()         { *m = Operator{} }
func (m *Operator) String() string { return proto.CompactTextString(m) }
func (*Operator) ProtoMessage()    {}
func (*Operator) Descriptor() ([]byte, []int) {
	return fileDescriptor_remoteid_2e8f532f1597596d, []int{3}
}
func (m *Operator) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Operator.Unmarshal(m, b)
}
func (m *Operator) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Operator.Marshal(b, m, deterministic)
}
func (dst *Operator) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Operator.Merge(dst, src)
}
func (m *Operator) XXX_Size() int {
	return xxx_messageInfo_Operator.Size(m)
}
func (m *Operator) XXX_DiscardUnknown() {
	xxx_messageInfo_Operator.DiscardUnknown(m)
}

var xxx_messageInfo_Operator proto.InternalMessageInfo

func (m *Operator) GetId() *ids.Operator {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *Operator) GetLocation() *geo.Coordinate2D {
	if m != nil {
		return m.Location
	}
	return nil
}

// Aircraft models the vehicle performing an operation.
type Aircraft struct {
	Type                 Aircraft_Type `protobuf:"varint,1,opt,name=type,proto3,enum=remoteid.Aircraft_Type" json:"type,omitempty"`
	Make                 string        `protobuf:"bytes,2,opt,name=make,proto3" json:"make,omitempty"`
	Model                string        `protobuf:"bytes,3,opt,name=model,proto3" json:"model,omitempty"`
	Serial               string        `protobuf:"bytes,4,opt,name=serial,proto3" json:"serial,omitempty"`
	Registration         string        `protobuf:"bytes,5,opt,name=registration,proto3" json:"registration,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Aircraft) Reset()         { *m = Aircraft{} }
func (m *Aircraft) String() string { return proto.CompactTextString(m) }
func (*Aircraft) ProtoMessage()    {}
func (*Aircraft) Descriptor() ([]byte, []int) {
	return fileDescriptor_remoteid_2e8f532f1597596d, []int{4}
}
func (m *Aircraft) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Aircraft.Unmarshal(m, b)
}
func (m *Aircraft) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Aircraft.Marshal(b, m, deterministic)
}
func (dst *Aircraft) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Aircraft.Merge(dst, src)
}
func (m *Aircraft) XXX_Size() int {
	return xxx_messageInfo_Aircraft.Size(m)
}
func (m *Aircraft) XXX_DiscardUnknown() {
	xxx_messageInfo_Aircraft.DiscardUnknown(m)
}

var xxx_messageInfo_Aircraft proto.InternalMessageInfo

func (m *Aircraft) GetType() Aircraft_Type {
	if m != nil {
		return m.Type
	}
	return Aircraft_UNKNOWN
}

func (m *Aircraft) GetMake() string {
	if m != nil {
		return m.Make
	}
	return ""
}

func (m *Aircraft) GetModel() string {
	if m != nil {
		return m.Model
	}
	return ""
}

func (m *Aircraft) GetSerial() string {
	if m != nil {
		return m.Serial
	}
	return ""
}

func (m *Aircraft) GetRegistration() string {
	if m != nil {
		return m.Registration
	}
	return ""
}

func init() {
	proto.RegisterType((*MonitorAreaParameters)(nil), "remoteid.MonitorAreaParameters")
	proto.RegisterType((*MonitorAreaResponse)(nil), "remoteid.MonitorAreaResponse")
	proto.RegisterType((*MonitorAreaResponse_Added)(nil), "remoteid.MonitorAreaResponse.Added")
	proto.RegisterType((*MonitorAreaResponse_Updated)(nil), "remoteid.MonitorAreaResponse.Updated")
	proto.RegisterType((*MonitorAreaResponse_Removed)(nil), "remoteid.MonitorAreaResponse.Removed")
	proto.RegisterType((*Operation)(nil), "remoteid.Operation")
	proto.RegisterType((*Operation_State)(nil), "remoteid.Operation.State")
	proto.RegisterType((*Operator)(nil), "remoteid.Operator")
	proto.RegisterType((*Aircraft)(nil), "remoteid.Aircraft")
	proto.RegisterEnum("remoteid.Aircraft_Type", Aircraft_Type_name, Aircraft_Type_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// RemoteIDClient is the client API for RemoteID service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RemoteIDClient interface {
	// MonitorArea monitors a given area for active operations.
	MonitorArea(ctx context.Context, in *MonitorAreaParameters, opts ...grpc.CallOption) (RemoteID_MonitorAreaClient, error)
}

type remoteIDClient struct {
	cc *grpc.ClientConn
}

func NewRemoteIDClient(cc *grpc.ClientConn) RemoteIDClient {
	return &remoteIDClient{cc}
}

func (c *remoteIDClient) MonitorArea(ctx context.Context, in *MonitorAreaParameters, opts ...grpc.CallOption) (RemoteID_MonitorAreaClient, error) {
	stream, err := c.cc.NewStream(ctx, &_RemoteID_serviceDesc.Streams[0], "/remoteid.RemoteID/MonitorArea", opts...)
	if err != nil {
		return nil, err
	}
	x := &remoteIDMonitorAreaClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type RemoteID_MonitorAreaClient interface {
	Recv() (*MonitorAreaResponse, error)
	grpc.ClientStream
}

type remoteIDMonitorAreaClient struct {
	grpc.ClientStream
}

func (x *remoteIDMonitorAreaClient) Recv() (*MonitorAreaResponse, error) {
	m := new(MonitorAreaResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// RemoteIDServer is the server API for RemoteID service.
type RemoteIDServer interface {
	// MonitorArea monitors a given area for active operations.
	MonitorArea(*MonitorAreaParameters, RemoteID_MonitorAreaServer) error
}

func RegisterRemoteIDServer(s *grpc.Server, srv RemoteIDServer) {
	s.RegisterService(&_RemoteID_serviceDesc, srv)
}

func _RemoteID_MonitorArea_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(MonitorAreaParameters)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RemoteIDServer).MonitorArea(m, &remoteIDMonitorAreaServer{stream})
}

type RemoteID_MonitorAreaServer interface {
	Send(*MonitorAreaResponse) error
	grpc.ServerStream
}

type remoteIDMonitorAreaServer struct {
	grpc.ServerStream
}

func (x *remoteIDMonitorAreaServer) Send(m *MonitorAreaResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _RemoteID_serviceDesc = grpc.ServiceDesc{
	ServiceName: "remoteid.RemoteID",
	HandlerType: (*RemoteIDServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "MonitorArea",
			Handler:       _RemoteID_MonitorArea_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "remoteid/remoteid.proto",
}

func init() { proto.RegisterFile("remoteid/remoteid.proto", fileDescriptor_remoteid_2e8f532f1597596d) }

var fileDescriptor_remoteid_2e8f532f1597596d = []byte{
	// 920 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x95, 0x5d, 0x6f, 0xdb, 0x36,
	0x17, 0xc7, 0xe3, 0xd8, 0x8e, 0xa5, 0xe3, 0xbc, 0xe8, 0x61, 0x9e, 0xb5, 0x9e, 0xd1, 0x2e, 0x81,
	0x87, 0x01, 0x1e, 0xb6, 0x4a, 0xab, 0xbb, 0x8b, 0x62, 0xbd, 0x92, 0x6d, 0x25, 0x36, 0xe2, 0x59,
	0x06, 0xa3, 0x64, 0x6f, 0x17, 0x06, 0x63, 0xd1, 0x1a, 0x31, 0xcb, 0x14, 0x48, 0xba, 0x58, 0x80,
	0x7d, 0x84, 0x7d, 0xb0, 0x7d, 0x84, 0x7d, 0x88, 0xdd, 0xef, 0x76, 0x10, 0xf5, 0x62, 0x67, 0x0b,
	0xda, 0xde, 0xe9, 0xf0, 0xfc, 0xfe, 0x87, 0xfc, 0x1f, 0x92, 0x22, 0x3c, 0x15, 0x34, 0xe6, 0x8a,
	0xb2, 0xd0, 0x29, 0x3e, 0xec, 0x44, 0x70, 0xc5, 0x91, 0x51, 0xc4, 0xed, 0x23, 0x16, 0x4a, 0x87,
	0x85, 0x32, 0x4b, 0xb4, 0x8f, 0x22, 0xca, 0x9d, 0x88, 0xf2, 0x3c, 0x3c, 0x8b, 0x29, 0x91, 0x1b,
	0x41, 0x63, 0xba, 0x56, 0xd2, 0xd9, 0x0d, 0x0a, 0x20, 0xe2, 0x3c, 0x5a, 0x51, 0x47, 0x47, 0x77,
	0x9b, 0xa5, 0xa3, 0x58, 0x4c, 0xa5, 0x22, 0x71, 0x92, 0x01, 0x9d, 0x6b, 0xf8, 0xe8, 0x5b, 0xbe,
	0x66, 0x8a, 0x0b, 0x57, 0x50, 0x32, 0x23, 0x82, 0xc4, 0x54, 0x51, 0x21, 0xd1, 0x37, 0x60, 0x11,
	0x41, 0xc9, 0x9c, 0x2f, 0xe7, 0x6c, 0xad, 0xa8, 0xa0, 0x52, 0xb5, 0x2a, 0xe7, 0x95, 0x6e, 0xb3,
	0x67, 0xd9, 0xe9, 0x02, 0xfa, 0x7c, 0xb3, 0x0e, 0xd9, 0x3a, 0xea, 0xf3, 0x5f, 0xf1, 0x71, 0x4a,
	0xfa, 0xcb, 0x71, 0xce, 0x75, 0xfe, 0xae, 0xc2, 0xe9, 0x4e, 0x55, 0x4c, 0x65, 0xc2, 0xd7, 0x92,
	0xa2, 0x37, 0x50, 0x27, 0x61, 0x48, 0xc3, 0xbc, 0xd0, 0xa7, 0x76, 0x69, 0xfb, 0x11, 0xda, 0x76,
	0x53, 0x74, 0xb4, 0x87, 0x33, 0x0d, 0x72, 0xa1, 0xb1, 0x49, 0x42, 0xa2, 0x68, 0xd8, 0xda, 0xd7,
	0xf2, 0xcf, 0xde, 0x2d, 0xbf, 0xc9, 0xe0, 0xd1, 0x1e, 0x2e, 0x74, 0x69, 0x89, 0x54, 0xf2, 0x96,
	0x86, 0xad, 0xea, 0x87, 0x94, 0xc0, 0x19, 0x9c, 0x96, 0xc8, 0x75, 0x6d, 0x06, 0x75, 0xbd, 0x2e,
	0xf4, 0x12, 0x4c, 0x9e, 0x50, 0x41, 0x14, 0xe3, 0xeb, 0xdc, 0xcf, 0xe9, 0xb6, 0x9a, 0x5f, 0xa4,
	0xf0, 0x96, 0x42, 0x2f, 0xc0, 0x4c, 0xb8, 0x64, 0xe9, 0xb7, 0x6c, 0xed, 0x9f, 0x57, 0xbb, 0xcd,
	0xde, 0x89, 0xee, 0xe5, 0x2c, 0x1f, 0xfd, 0x7a, 0x88, 0xb7, 0x44, 0xfb, 0x37, 0x68, 0xe4, 0x1e,
	0xd0, 0xab, 0x0f, 0x9b, 0x6c, 0xb4, 0xb7, 0x3b, 0xdd, 0x4b, 0xa8, 0x4b, 0x45, 0x14, 0xcd, 0xdb,
	0xf5, 0xf1, 0x23, 0x02, 0xfb, 0x3a, 0x05, 0xd2, 0x1e, 0x6b, 0xb2, 0x6f, 0x42, 0x23, 0xa4, 0x8a,
	0xb0, 0x95, 0x6c, 0x7f, 0x0e, 0x8d, 0xdc, 0x3e, 0xfa, 0x04, 0xf6, 0x59, 0xb1, 0x67, 0xc7, 0x76,
	0x7a, 0x18, 0xb7, 0xf6, 0xf6, 0x59, 0xb8, 0xa3, 0xea, 0xfc, 0x51, 0x05, 0xb3, 0x4c, 0xbe, 0x4f,
	0x88, 0x6c, 0x30, 0xb2, 0xe5, 0x72, 0x91, 0x2f, 0x12, 0xfd, 0x7b, 0x91, 0x5c, 0xe0, 0x92, 0x49,
	0x79, 0xc2, 0xc4, 0x42, 0x90, 0xa5, 0xca, 0x37, 0x70, 0x87, 0x77, 0xf3, 0x0c, 0x2e, 0x19, 0xd4,
	0x05, 0x23, 0xa2, 0x3c, 0xa6, 0x4a, 0xdc, 0xb7, 0x6a, 0x9a, 0x3f, 0xcc, 0xfb, 0xbd, 0xba, 0x8f,
	0xf8, 0x1a, 0x97, 0x59, 0xd4, 0x82, 0x46, 0xb2, 0x11, 0x09, 0x97, 0xb4, 0x55, 0x3f, 0xaf, 0x74,
	0x4d, 0x5c, 0x84, 0xe8, 0x19, 0x98, 0x92, 0xc5, 0x9b, 0x95, 0x3e, 0x78, 0x07, 0xe7, 0x95, 0xae,
	0x81, 0xb7, 0x03, 0xed, 0x3f, 0x2b, 0x50, 0xd7, 0x3d, 0x7c, 0xaf, 0xd7, 0xd7, 0x60, 0x96, 0x77,
	0x2f, 0x37, 0xdb, 0xb6, 0xb3, 0xdb, 0x69, 0x17, 0xb7, 0xd3, 0x0e, 0x0a, 0x02, 0x6f, 0x61, 0xf4,
	0x06, 0x8c, 0xe2, 0x50, 0xe4, 0xae, 0xcf, 0xec, 0x07, 0x57, 0xbd, 0x38, 0x3e, 0xb6, 0x7b, 0x27,
	0xf9, 0x6a, 0xa3, 0x28, 0x2e, 0x05, 0xe8, 0x35, 0x18, 0x6f, 0xe9, 0x8a, 0x2f, 0x98, 0x2a, 0x5a,
	0xf0, 0xec, 0xa1, 0xf8, 0x36, 0xcf, 0xa6, 0x4d, 0x21, 0x02, 0x97, 0x74, 0xe7, 0x7b, 0x30, 0x8a,
	0x2d, 0x40, 0xcf, 0x77, 0xcc, 0x1d, 0xed, 0x98, 0xe3, 0x42, 0x7b, 0x7b, 0x01, 0xc6, 0x8a, 0x2f,
	0xb2, 0xd3, 0x99, 0x59, 0xfb, 0x9f, 0xee, 0xf3, 0x80, 0x73, 0x11, 0xb2, 0x35, 0x51, 0xb4, 0x37,
	0xc4, 0x25, 0xd2, 0xf9, 0xbd, 0x0a, 0x46, 0xb1, 0x5b, 0xe8, 0x0b, 0xa8, 0xa9, 0xfb, 0x84, 0xea,
	0xe2, 0xc7, 0xbd, 0xa7, 0xff, 0xdd, 0x4f, 0x3b, 0xb8, 0x4f, 0x28, 0xd6, 0x10, 0x42, 0x50, 0x8b,
	0xc9, 0x2f, 0xd9, 0x89, 0x36, 0xb1, 0xfe, 0x46, 0xff, 0x87, 0x7a, 0xcc, 0x43, 0xba, 0xd2, 0xbd,
	0x31, 0x71, 0x16, 0xa0, 0x27, 0x70, 0x20, 0xa9, 0x60, 0x64, 0xa5, 0x5d, 0x9b, 0x38, 0x8f, 0x50,
	0x07, 0x0e, 0x05, 0x8d, 0x98, 0x54, 0xf9, 0x65, 0xca, 0x76, 0xfb, 0xc1, 0x58, 0xe7, 0xaf, 0x0a,
	0xd4, 0xd2, 0x49, 0x51, 0x13, 0x1a, 0x37, 0xd3, 0xab, 0xa9, 0xff, 0xdd, 0xd4, 0xda, 0x43, 0x87,
	0x60, 0xb8, 0x63, 0x3c, 0x9b, 0xb8, 0x53, 0xcf, 0xaa, 0xa0, 0x63, 0x00, 0xec, 0x07, 0x3e, 0x1e,
	0x60, 0xf7, 0x22, 0xb0, 0xf6, 0xd1, 0x11, 0x98, 0x97, 0x3f, 0x60, 0x3f, 0x4b, 0x57, 0x91, 0x01,
	0xb5, 0xdb, 0xc0, 0x9f, 0x58, 0x35, 0x74, 0x02, 0x4d, 0x1f, 0x4f, 0xc7, 0xc1, 0xc8, 0x9f, 0x05,
	0x1e, 0xb6, 0xea, 0x08, 0xe0, 0xe0, 0x72, 0x32, 0x1e, 0x7a, 0xd8, 0x3a, 0x48, 0xb1, 0xab, 0x71,
	0xe0, 0x59, 0x8d, 0x14, 0xbb, 0xc0, 0x9e, 0x37, 0xef, 0xbb, 0x13, 0xdf, 0x9f, 0x5a, 0x06, 0x3a,
	0x85, 0x93, 0x81, 0x3b, 0x0b, 0xc6, 0xb7, 0x7a, 0x4c, 0x0f, 0x9a, 0xe9, 0x82, 0xdc, 0x31, 0xbe,
	0x1e, 0x8d, 0x67, 0x16, 0xa0, 0x36, 0x3c, 0xd1, 0x92, 0x0b, 0x77, 0x32, 0x99, 0xfb, 0x78, 0x3e,
	0x73, 0xb1, 0x3b, 0x18, 0xdd, 0x04, 0x9e, 0xd5, 0x4c, 0x27, 0xc1, 0xfe, 0xe0, 0xca, 0x0b, 0xac,
	0xc3, 0xb4, 0xd2, 0x25, 0xf6, 0x6f, 0xa6, 0xc3, 0xb9, 0xdf, 0xbf, 0x0e, 0xdc, 0xc1, 0xc4, 0xb3,
	0x8e, 0x90, 0x09, 0x75, 0x3f, 0x18, 0x79, 0xd8, 0x3a, 0xee, 0xfd, 0x04, 0x06, 0xd6, 0x4d, 0x1f,
	0x0f, 0x91, 0x0f, 0xcd, 0x9d, 0x1f, 0x21, 0x3a, 0x7b, 0xf4, 0xff, 0xb8, 0x7d, 0x25, 0xda, 0xcf,
	0xdf, 0xf9, 0x03, 0xfd, 0xaa, 0xd2, 0xb7, 0x7f, 0xfc, 0x32, 0x62, 0xea, 0xe7, 0xcd, 0x9d, 0xbd,
	0xe0, 0xb1, 0x43, 0x98, 0x88, 0x49, 0xe2, 0xe8, 0x07, 0x65, 0x49, 0x16, 0x54, 0x3a, 0x52, 0x2c,
	0x9c, 0x88, 0x97, 0xef, 0xdf, 0xdd, 0x81, 0xbe, 0x0b, 0xaf, 0xfe, 0x09, 0x00, 0x00, 0xff, 0xff,
	0xb4, 0x92, 0x1e, 0xb1, 0x1b, 0x07, 0x00, 0x00,
}
