// Code generated by protoc-gen-go. DO NOT EDIT.
// source: tracking/track.proto

package tracking

import (
	fmt "fmt"
	_ "github.com/airmap/interfaces/grpc"
	measurements "github.com/airmap/interfaces/grpc/measurements"
	proto "github.com/golang/protobuf/proto"
	any "github.com/golang/protobuf/ptypes/any"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Track models a single track observation.
type Track struct {
	Observed             *timestamp.Timestamp      `protobuf:"bytes,1,opt,name=observed,proto3" json:"observed,omitempty"`
	Position             *measurements.Position    `protobuf:"bytes,2,opt,name=position,proto3" json:"position,omitempty"`
	Velocity             *measurements.Velocity    `protobuf:"bytes,3,opt,name=velocity,proto3" json:"velocity,omitempty"`
	Orientation          *measurements.Orientation `protobuf:"bytes,4,opt,name=orientation,proto3" json:"orientation,omitempty"`
	Emitter              Emitter                   `protobuf:"varint,5,opt,name=emitter,proto3,enum=tracking.Emitter" json:"emitter,omitempty"`
	Sensor               *Sensor                   `protobuf:"bytes,6,opt,name=sensor,proto3" json:"sensor,omitempty"`
	Identities           []*Identity               `protobuf:"bytes,7,rep,name=identities,proto3" json:"identities,omitempty"`
	Flags                *Track_Flags              `protobuf:"bytes,8,opt,name=flags,proto3" json:"flags,omitempty"`
	Details              []*any.Any                `protobuf:"bytes,1024,rep,name=details,proto3" json:"details,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *Track) Reset()         { *m = Track{} }
func (m *Track) String() string { return proto.CompactTextString(m) }
func (*Track) ProtoMessage()    {}
func (*Track) Descriptor() ([]byte, []int) {
	return fileDescriptor_560f96cb68e45a5e, []int{0}
}

func (m *Track) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Track.Unmarshal(m, b)
}
func (m *Track) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Track.Marshal(b, m, deterministic)
}
func (m *Track) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Track.Merge(m, src)
}
func (m *Track) XXX_Size() int {
	return xxx_messageInfo_Track.Size(m)
}
func (m *Track) XXX_DiscardUnknown() {
	xxx_messageInfo_Track.DiscardUnknown(m)
}

var xxx_messageInfo_Track proto.InternalMessageInfo

func (m *Track) GetObserved() *timestamp.Timestamp {
	if m != nil {
		return m.Observed
	}
	return nil
}

func (m *Track) GetPosition() *measurements.Position {
	if m != nil {
		return m.Position
	}
	return nil
}

func (m *Track) GetVelocity() *measurements.Velocity {
	if m != nil {
		return m.Velocity
	}
	return nil
}

func (m *Track) GetOrientation() *measurements.Orientation {
	if m != nil {
		return m.Orientation
	}
	return nil
}

func (m *Track) GetEmitter() Emitter {
	if m != nil {
		return m.Emitter
	}
	return Emitter_EMITTER_UNKNOWN
}

func (m *Track) GetSensor() *Sensor {
	if m != nil {
		return m.Sensor
	}
	return nil
}

func (m *Track) GetIdentities() []*Identity {
	if m != nil {
		return m.Identities
	}
	return nil
}

func (m *Track) GetFlags() *Track_Flags {
	if m != nil {
		return m.Flags
	}
	return nil
}

func (m *Track) GetDetails() []*any.Any {
	if m != nil {
		return m.Details
	}
	return nil
}

type Track_Flags struct {
	Coasted              bool     `protobuf:"varint,1,opt,name=coasted,proto3" json:"coasted,omitempty"`
	Shadowed             bool     `protobuf:"varint,2,opt,name=shadowed,proto3" json:"shadowed,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Track_Flags) Reset()         { *m = Track_Flags{} }
func (m *Track_Flags) String() string { return proto.CompactTextString(m) }
func (*Track_Flags) ProtoMessage()    {}
func (*Track_Flags) Descriptor() ([]byte, []int) {
	return fileDescriptor_560f96cb68e45a5e, []int{0, 0}
}

func (m *Track_Flags) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Track_Flags.Unmarshal(m, b)
}
func (m *Track_Flags) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Track_Flags.Marshal(b, m, deterministic)
}
func (m *Track_Flags) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Track_Flags.Merge(m, src)
}
func (m *Track_Flags) XXX_Size() int {
	return xxx_messageInfo_Track_Flags.Size(m)
}
func (m *Track_Flags) XXX_DiscardUnknown() {
	xxx_messageInfo_Track_Flags.DiscardUnknown(m)
}

var xxx_messageInfo_Track_Flags proto.InternalMessageInfo

func (m *Track_Flags) GetCoasted() bool {
	if m != nil {
		return m.Coasted
	}
	return false
}

func (m *Track_Flags) GetShadowed() bool {
	if m != nil {
		return m.Shadowed
	}
	return false
}

// Batch models a batch of tracks.
type Track_Batch struct {
	Tracks               []*Track `protobuf:"bytes,1,rep,name=tracks,proto3" json:"tracks,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Track_Batch) Reset()         { *m = Track_Batch{} }
func (m *Track_Batch) String() string { return proto.CompactTextString(m) }
func (*Track_Batch) ProtoMessage()    {}
func (*Track_Batch) Descriptor() ([]byte, []int) {
	return fileDescriptor_560f96cb68e45a5e, []int{0, 1}
}

func (m *Track_Batch) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Track_Batch.Unmarshal(m, b)
}
func (m *Track_Batch) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Track_Batch.Marshal(b, m, deterministic)
}
func (m *Track_Batch) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Track_Batch.Merge(m, src)
}
func (m *Track_Batch) XXX_Size() int {
	return xxx_messageInfo_Track_Batch.Size(m)
}
func (m *Track_Batch) XXX_DiscardUnknown() {
	xxx_messageInfo_Track_Batch.DiscardUnknown(m)
}

var xxx_messageInfo_Track_Batch proto.InternalMessageInfo

func (m *Track_Batch) GetTracks() []*Track {
	if m != nil {
		return m.Tracks
	}
	return nil
}

func init() {
	proto.RegisterType((*Track)(nil), "tracking.Track")
	proto.RegisterType((*Track_Flags)(nil), "tracking.Track.Flags")
	proto.RegisterType((*Track_Batch)(nil), "tracking.Track.Batch")
}

func init() { proto.RegisterFile("tracking/track.proto", fileDescriptor_560f96cb68e45a5e) }

var fileDescriptor_560f96cb68e45a5e = []byte{
	// 452 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0xcd, 0x8e, 0xd3, 0x30,
	0x14, 0x85, 0x15, 0xa6, 0x69, 0x23, 0x57, 0x82, 0xc1, 0x1a, 0x06, 0x4f, 0x24, 0x44, 0xc5, 0x86,
	0x0a, 0x90, 0x03, 0x41, 0x20, 0x36, 0x2c, 0xa6, 0x12, 0x48, 0xac, 0x40, 0x66, 0xc4, 0x82, 0x9d,
	0x9b, 0xdc, 0xa6, 0x16, 0x8d, 0x1d, 0xd9, 0xb7, 0x03, 0xb3, 0x9b, 0xa7, 0xe1, 0x91, 0x78, 0x1e,
	0x34, 0x8e, 0x9d, 0x76, 0x7e, 0x76, 0xf6, 0x3d, 0xdf, 0xb1, 0x8f, 0xce, 0x25, 0x47, 0x68, 0x65,
	0xf5, 0x4b, 0xe9, 0xa6, 0xf0, 0x07, 0xde, 0x59, 0x83, 0x86, 0x66, 0x71, 0x9a, 0x9f, 0x34, 0xc6,
	0x34, 0x1b, 0x28, 0xfc, 0x7c, 0xb9, 0x5d, 0x15, 0x52, 0x5f, 0xf4, 0x50, 0xfe, 0xf4, 0xa6, 0x84,
	0xaa, 0x05, 0x87, 0xb2, 0xed, 0x02, 0x70, 0x08, 0x7f, 0x10, 0xb4, 0x53, 0x46, 0xbb, 0x68, 0x69,
	0x41, 0xba, 0xad, 0x85, 0x16, 0x34, 0xba, 0x62, 0xff, 0x12, 0x80, 0xe3, 0x21, 0x0e, 0xb4, 0x0a,
	0x11, 0xec, 0xad, 0xb9, 0x03, 0xed, 0x8c, 0x8d, 0xfc, 0xe3, 0x61, 0xae, 0x6a, 0xd0, 0xa8, 0x30,
	0x84, 0x7b, 0xf6, 0x6f, 0x44, 0xd2, 0xb3, 0x2b, 0x8d, 0xbe, 0x27, 0x99, 0x59, 0x3a, 0xb0, 0xe7,
	0x50, 0xb3, 0x64, 0x96, 0xcc, 0xa7, 0x65, 0xce, 0xfb, 0xe4, 0x3c, 0x26, 0xe7, 0x67, 0x31, 0xb9,
	0x18, 0x58, 0x5a, 0x92, 0xac, 0x33, 0x4e, 0xa1, 0x32, 0x9a, 0xdd, 0xf3, 0xbe, 0x63, 0x7e, 0x2d,
	0xf1, 0xb7, 0xa0, 0x8a, 0x81, 0xa3, 0x1f, 0x48, 0x76, 0x0e, 0x1b, 0x53, 0x29, 0xbc, 0x60, 0x07,
	0x77, 0x79, 0x7e, 0x04, 0x75, 0x31, 0xba, 0xfc, 0xfb, 0x24, 0x11, 0x03, 0x4d, 0x4f, 0xc9, 0xd4,
	0x58, 0x05, 0x1a, 0xa5, 0xff, 0x70, 0xe4, 0xcd, 0x27, 0xd7, 0xcd, 0x5f, 0x77, 0x40, 0xf0, 0xef,
	0x7b, 0xe8, 0x1b, 0x32, 0x09, 0xa5, 0xb1, 0x74, 0x96, 0xcc, 0xef, 0x97, 0x0f, 0x79, 0x6c, 0x87,
	0x7f, 0xea, 0x85, 0x60, 0x8b, 0x1c, 0x9d, 0x93, 0x71, 0xdf, 0x27, 0x1b, 0xfb, 0x0f, 0x0f, 0x77,
	0x8e, 0xef, 0x7e, 0x2e, 0x82, 0x4e, 0x4b, 0x42, 0x42, 0xc3, 0x0a, 0x1c, 0x9b, 0xcc, 0x0e, 0xe6,
	0xd3, 0x92, 0xee, 0xe8, 0x2f, 0xa1, 0x7d, 0xb1, 0x47, 0xd1, 0x97, 0x24, 0x5d, 0x6d, 0x64, 0xe3,
	0x58, 0xe6, 0x1f, 0x7f, 0xb4, 0xc3, 0xfd, 0x66, 0xf8, 0xe7, 0x2b, 0x51, 0xf4, 0x0c, 0x7d, 0x47,
	0x26, 0x35, 0xa0, 0x54, 0x1b, 0xc7, 0x2e, 0x33, 0xff, 0xfc, 0xd1, 0xad, 0x35, 0x9d, 0xea, 0x58,
	0x5c, 0x64, 0xf3, 0x8f, 0x24, 0xf5, 0xcf, 0x50, 0x46, 0x26, 0x95, 0x91, 0x0e, 0xc3, 0x96, 0x33,
	0x11, 0xaf, 0x34, 0x27, 0x99, 0x5b, 0xcb, 0xda, 0xfc, 0x86, 0xda, 0x2f, 0x32, 0x13, 0xc3, 0x3d,
	0x7f, 0x4d, 0xd2, 0x85, 0xc4, 0x6a, 0x4d, 0x9f, 0x93, 0xb1, 0x4f, 0xe7, 0x58, 0xe2, 0x3f, 0x7f,
	0x70, 0x23, 0xac, 0x08, 0xf2, 0xe2, 0xd5, 0xcf, 0x17, 0x8d, 0xc2, 0xf5, 0x76, 0xc9, 0x2b, 0xd3,
	0x16, 0x52, 0xd9, 0x56, 0x76, 0x85, 0xd2, 0x08, 0x76, 0x25, 0x2b, 0x70, 0x45, 0x63, 0xbb, 0xaa,
	0x88, 0xde, 0xe5, 0xd8, 0x67, 0x7f, 0xfb, 0x3f, 0x00, 0x00, 0xff, 0xff, 0x1c, 0x0a, 0x96, 0x29,
	0x67, 0x03, 0x00, 0x00,
}
