// Code generated by protoc-gen-go. DO NOT EDIT.
// source: system/monitor.proto

package system // import "github.com/airmap/interfaces/src/go/system"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/airmap/interfaces/src/go"
import duration "github.com/golang/protobuf/ptypes/duration"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Monitor models parameters for configuration a monitoring component.
type Monitor struct {
	// period enables to configure the monitor with a configurable timeout/duration.
	//
	// Interpretation of this value is up to the respective component offering callers
	// to configure a monitor.
	Period               *duration.Duration `protobuf:"bytes,1,opt,name=period,proto3" json:"period,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *Monitor) Reset()         { *m = Monitor{} }
func (m *Monitor) String() string { return proto.CompactTextString(m) }
func (*Monitor) ProtoMessage()    {}
func (*Monitor) Descriptor() ([]byte, []int) {
	return fileDescriptor_monitor_1815c1ef8799c7ad, []int{0}
}
func (m *Monitor) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Monitor.Unmarshal(m, b)
}
func (m *Monitor) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Monitor.Marshal(b, m, deterministic)
}
func (dst *Monitor) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Monitor.Merge(dst, src)
}
func (m *Monitor) XXX_Size() int {
	return xxx_messageInfo_Monitor.Size(m)
}
func (m *Monitor) XXX_DiscardUnknown() {
	xxx_messageInfo_Monitor.DiscardUnknown(m)
}

var xxx_messageInfo_Monitor proto.InternalMessageInfo

func (m *Monitor) GetPeriod() *duration.Duration {
	if m != nil {
		return m.Period
	}
	return nil
}

func init() {
	proto.RegisterType((*Monitor)(nil), "system.Monitor")
}

func init() { proto.RegisterFile("system/monitor.proto", fileDescriptor_monitor_1815c1ef8799c7ad) }

var fileDescriptor_monitor_1815c1ef8799c7ad = []byte{
	// 170 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x34, 0xce, 0x31, 0xcb, 0xc2, 0x30,
	0x10, 0xc6, 0x71, 0xba, 0xf4, 0x85, 0xbe, 0x8b, 0x14, 0x07, 0xed, 0x20, 0xe2, 0x24, 0x22, 0x39,
	0xd4, 0xd5, 0x49, 0x5c, 0x5d, 0x1c, 0xdd, 0xd2, 0xf6, 0x1a, 0x0f, 0x4c, 0xae, 0x5c, 0xae, 0xa0,
	0xdf, 0x5e, 0x68, 0xea, 0xfa, 0xe7, 0xe1, 0xc7, 0x53, 0xcc, 0xe3, 0x27, 0x2a, 0x7a, 0xf0, 0x1c,
	0x48, 0x59, 0x4c, 0x2f, 0xac, 0x5c, 0xe6, 0xa9, 0x56, 0x2b, 0xc7, 0xec, 0x5e, 0x08, 0x63, 0xad,
	0x87, 0x0e, 0xda, 0x41, 0xac, 0x12, 0x87, 0xb4, 0xab, 0x66, 0xf8, 0x56, 0x0c, 0x91, 0x38, 0xc4,
	0x54, 0x36, 0xe7, 0xe2, 0xef, 0x96, 0xa8, 0xf2, 0x50, 0xe4, 0x3d, 0x0a, 0x71, 0xbb, 0xc8, 0xd6,
	0xd9, 0xf6, 0xff, 0xb8, 0x34, 0x49, 0x33, 0x3f, 0xcd, 0x5c, 0x27, 0xed, 0x3e, 0x0d, 0x2f, 0xfb,
	0xc7, 0xce, 0x91, 0x3e, 0x87, 0xda, 0x34, 0xec, 0xc1, 0x92, 0x78, 0xdb, 0x03, 0x05, 0x45, 0xe9,
	0x6c, 0x83, 0x11, 0xa2, 0x34, 0xe0, 0x18, 0xd2, 0xbb, 0x3a, 0x1f, 0xa1, 0xd3, 0x37, 0x00, 0x00,
	0xff, 0xff, 0x01, 0x4b, 0x60, 0xc6, 0xc4, 0x00, 0x00, 0x00,
}
