// Code generated by protoc-gen-go. DO NOT EDIT.
// source: geo/geo.proto

package geo // import "github.com/airmap/interfaces/src/go/geo"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/airmap/interfaces/src/go"
import units "github.com/airmap/interfaces/src/go/units"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Coordinate2D models a WGS84 latitude and longitude.
type Coordinate2D struct {
	Latitude             *units.Degrees      `protobuf:"bytes,1,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude            *units.Degrees      `protobuf:"bytes,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Error                *Coordinate2D_Error `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *Coordinate2D) Reset()         { *m = Coordinate2D{} }
func (m *Coordinate2D) String() string { return proto.CompactTextString(m) }
func (*Coordinate2D) ProtoMessage()    {}
func (*Coordinate2D) Descriptor() ([]byte, []int) {
	return fileDescriptor_geo_d7a960d67d37cdd8, []int{0}
}
func (m *Coordinate2D) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Coordinate2D.Unmarshal(m, b)
}
func (m *Coordinate2D) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Coordinate2D.Marshal(b, m, deterministic)
}
func (dst *Coordinate2D) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Coordinate2D.Merge(dst, src)
}
func (m *Coordinate2D) XXX_Size() int {
	return xxx_messageInfo_Coordinate2D.Size(m)
}
func (m *Coordinate2D) XXX_DiscardUnknown() {
	xxx_messageInfo_Coordinate2D.DiscardUnknown(m)
}

var xxx_messageInfo_Coordinate2D proto.InternalMessageInfo

func (m *Coordinate2D) GetLatitude() *units.Degrees {
	if m != nil {
		return m.Latitude
	}
	return nil
}

func (m *Coordinate2D) GetLongitude() *units.Degrees {
	if m != nil {
		return m.Longitude
	}
	return nil
}

func (m *Coordinate2D) GetError() *Coordinate2D_Error {
	if m != nil {
		return m.Error
	}
	return nil
}

// Error models the inherent error in a coordinate measurement.
type Coordinate2D_Error struct {
	Latitude             *units.Degrees `protobuf:"bytes,1,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude            *units.Degrees `protobuf:"bytes,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Coordinate2D_Error) Reset()         { *m = Coordinate2D_Error{} }
func (m *Coordinate2D_Error) String() string { return proto.CompactTextString(m) }
func (*Coordinate2D_Error) ProtoMessage()    {}
func (*Coordinate2D_Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_geo_d7a960d67d37cdd8, []int{0, 0}
}
func (m *Coordinate2D_Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Coordinate2D_Error.Unmarshal(m, b)
}
func (m *Coordinate2D_Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Coordinate2D_Error.Marshal(b, m, deterministic)
}
func (dst *Coordinate2D_Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Coordinate2D_Error.Merge(dst, src)
}
func (m *Coordinate2D_Error) XXX_Size() int {
	return xxx_messageInfo_Coordinate2D_Error.Size(m)
}
func (m *Coordinate2D_Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Coordinate2D_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Coordinate2D_Error proto.InternalMessageInfo

func (m *Coordinate2D_Error) GetLatitude() *units.Degrees {
	if m != nil {
		return m.Latitude
	}
	return nil
}

func (m *Coordinate2D_Error) GetLongitude() *units.Degrees {
	if m != nil {
		return m.Longitude
	}
	return nil
}

// BoundingBox models a geographic bounds
type BoundingBox struct {
	Southwest            *Coordinate2D `protobuf:"bytes,1,opt,name=southwest,proto3" json:"southwest,omitempty"`
	Northeast            *Coordinate2D `protobuf:"bytes,2,opt,name=northeast,proto3" json:"northeast,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *BoundingBox) Reset()         { *m = BoundingBox{} }
func (m *BoundingBox) String() string { return proto.CompactTextString(m) }
func (*BoundingBox) ProtoMessage()    {}
func (*BoundingBox) Descriptor() ([]byte, []int) {
	return fileDescriptor_geo_d7a960d67d37cdd8, []int{1}
}
func (m *BoundingBox) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BoundingBox.Unmarshal(m, b)
}
func (m *BoundingBox) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BoundingBox.Marshal(b, m, deterministic)
}
func (dst *BoundingBox) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BoundingBox.Merge(dst, src)
}
func (m *BoundingBox) XXX_Size() int {
	return xxx_messageInfo_BoundingBox.Size(m)
}
func (m *BoundingBox) XXX_DiscardUnknown() {
	xxx_messageInfo_BoundingBox.DiscardUnknown(m)
}

var xxx_messageInfo_BoundingBox proto.InternalMessageInfo

func (m *BoundingBox) GetSouthwest() *Coordinate2D {
	if m != nil {
		return m.Southwest
	}
	return nil
}

func (m *BoundingBox) GetNortheast() *Coordinate2D {
	if m != nil {
		return m.Northeast
	}
	return nil
}

// LinearRing models an array of point coordinates where the first and last point as equal.
type LinearRing struct {
	Coordinates          []*Coordinate2D `protobuf:"bytes,1,rep,name=coordinates,proto3" json:"coordinates,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *LinearRing) Reset()         { *m = LinearRing{} }
func (m *LinearRing) String() string { return proto.CompactTextString(m) }
func (*LinearRing) ProtoMessage()    {}
func (*LinearRing) Descriptor() ([]byte, []int) {
	return fileDescriptor_geo_d7a960d67d37cdd8, []int{2}
}
func (m *LinearRing) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LinearRing.Unmarshal(m, b)
}
func (m *LinearRing) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LinearRing.Marshal(b, m, deterministic)
}
func (dst *LinearRing) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LinearRing.Merge(dst, src)
}
func (m *LinearRing) XXX_Size() int {
	return xxx_messageInfo_LinearRing.Size(m)
}
func (m *LinearRing) XXX_DiscardUnknown() {
	xxx_messageInfo_LinearRing.DiscardUnknown(m)
}

var xxx_messageInfo_LinearRing proto.InternalMessageInfo

func (m *LinearRing) GetCoordinates() []*Coordinate2D {
	if m != nil {
		return m.Coordinates
	}
	return nil
}

// Polygon models an array of LinearRings where the first ring is the exterior ring and subsequent rings
// represent the interior rings/cutouts.
type Polygon struct {
	Rings                []*LinearRing `protobuf:"bytes,1,rep,name=rings,proto3" json:"rings,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Polygon) Reset()         { *m = Polygon{} }
func (m *Polygon) String() string { return proto.CompactTextString(m) }
func (*Polygon) ProtoMessage()    {}
func (*Polygon) Descriptor() ([]byte, []int) {
	return fileDescriptor_geo_d7a960d67d37cdd8, []int{3}
}
func (m *Polygon) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Polygon.Unmarshal(m, b)
}
func (m *Polygon) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Polygon.Marshal(b, m, deterministic)
}
func (dst *Polygon) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Polygon.Merge(dst, src)
}
func (m *Polygon) XXX_Size() int {
	return xxx_messageInfo_Polygon.Size(m)
}
func (m *Polygon) XXX_DiscardUnknown() {
	xxx_messageInfo_Polygon.DiscardUnknown(m)
}

var xxx_messageInfo_Polygon proto.InternalMessageInfo

func (m *Polygon) GetRings() []*LinearRing {
	if m != nil {
		return m.Rings
	}
	return nil
}

func init() {
	proto.RegisterType((*Coordinate2D)(nil), "geo.Coordinate2D")
	proto.RegisterType((*Coordinate2D_Error)(nil), "geo.Coordinate2D.Error")
	proto.RegisterType((*BoundingBox)(nil), "geo.BoundingBox")
	proto.RegisterType((*LinearRing)(nil), "geo.LinearRing")
	proto.RegisterType((*Polygon)(nil), "geo.Polygon")
}

func init() { proto.RegisterFile("geo/geo.proto", fileDescriptor_geo_d7a960d67d37cdd8) }

var fileDescriptor_geo_d7a960d67d37cdd8 = []byte{
	// 366 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x92, 0xb1, 0x4e, 0xc2, 0x50,
	0x14, 0x86, 0x5b, 0x10, 0xb5, 0x17, 0x51, 0xb9, 0x83, 0x92, 0x26, 0x24, 0xa4, 0x89, 0x51, 0x97,
	0xd6, 0xc0, 0x64, 0x5c, 0xb0, 0xa2, 0x71, 0x70, 0x30, 0x1d, 0x1c, 0xdc, 0x4a, 0x39, 0x5c, 0x6e,
	0x02, 0xf7, 0x90, 0x7b, 0x6f, 0x23, 0x4e, 0xf2, 0x1c, 0x8e, 0x0e, 0x3c, 0x87, 0x4f, 0xe1, 0xf3,
	0x98, 0xb6, 0x48, 0x1b, 0x24, 0xa1, 0x43, 0x93, 0xfe, 0xe7, 0xff, 0xbf, 0x9e, 0x3f, 0x39, 0xa4,
	0xc6, 0x00, 0x3d, 0x06, 0xe8, 0x4e, 0x25, 0x6a, 0xa4, 0x65, 0x06, 0x68, 0x1f, 0xc3, 0x4c, 0x83,
	0x50, 0x1c, 0x85, 0xca, 0x64, 0xbb, 0x1e, 0x0b, 0xae, 0x95, 0x97, 0xbe, 0x97, 0xd2, 0x49, 0x26,
	0xad, 0x5b, 0x9d, 0x9f, 0x12, 0x39, 0xb8, 0x43, 0x94, 0x03, 0x2e, 0x42, 0x0d, 0xed, 0x1e, 0x7d,
	0x20, 0xfb, 0xe3, 0x50, 0x73, 0x1d, 0x0f, 0xa0, 0x61, 0xb6, 0xcc, 0x8b, 0x6a, 0xfb, 0xd0, 0xcd,
	0x40, 0x3d, 0x60, 0x12, 0x40, 0xf9, 0xf6, 0xe7, 0xa2, 0x69, 0x59, 0x46, 0xf2, 0xcc, 0x5f, 0xbe,
	0xbf, 0x0a, 0x1f, 0xdd, 0x60, 0x95, 0xa5, 0x8f, 0xc4, 0x1a, 0xa3, 0x60, 0x19, 0xa8, 0xb4, 0x15,
	0x34, 0x2c, 0x82, 0x86, 0xdd, 0x20, 0x0f, 0xd3, 0x0e, 0xa9, 0x80, 0x94, 0x28, 0x1b, 0xe5, 0x94,
	0x72, 0xea, 0x26, 0xfd, 0x8b, 0x3b, 0xbb, 0xf7, 0xc9, 0xd8, 0xdf, 0x99, 0x2f, 0x9a, 0x66, 0x90,
	0x79, 0xed, 0x0f, 0x52, 0x49, 0x55, 0x7a, 0xbd, 0xb5, 0x4f, 0x2d, 0x5f, 0xc3, 0x30, 0x8c, 0x42,
	0x85, 0x9b, 0xed, 0x15, 0xd6, 0xb2, 0xb9, 0xdf, 0x41, 0x52, 0xf5, 0x31, 0x16, 0x03, 0x2e, 0x98,
	0x8f, 0x33, 0xea, 0x11, 0x4b, 0x61, 0xac, 0x47, 0x6f, 0xa0, 0xf4, 0x72, 0x8f, 0xfa, 0xbf, 0x22,
	0x41, 0xee, 0x49, 0x02, 0x02, 0xa5, 0x1e, 0x41, 0xa8, 0xf4, 0xf2, 0xe7, 0x9b, 0x02, 0x2b, 0x8f,
	0x73, 0x4b, 0xc8, 0x13, 0x17, 0x10, 0xca, 0x80, 0x0b, 0x46, 0x3b, 0xa4, 0x1a, 0xad, 0x8c, 0xaa,
	0x61, 0xb6, 0xca, 0x9b, 0x01, 0x45, 0x97, 0x73, 0x45, 0xf6, 0x9e, 0x71, 0xfc, 0xce, 0x50, 0xd0,
	0x33, 0x52, 0x91, 0x5c, 0xb0, 0xbf, 0xe4, 0x51, 0x9a, 0xcc, 0xf9, 0x41, 0x36, 0xf5, 0x2f, 0x5f,
	0xcf, 0x19, 0xd7, 0xa3, 0xb8, 0xef, 0x46, 0x38, 0xf1, 0x42, 0x2e, 0x27, 0xe1, 0xd4, 0xe3, 0x42,
	0x83, 0x1c, 0x86, 0x11, 0x28, 0x4f, 0xc9, 0xc8, 0x63, 0xe9, 0xc5, 0xf6, 0x77, 0xd3, 0x83, 0xeb,
	0xfc, 0x06, 0x00, 0x00, 0xff, 0xff, 0x68, 0x27, 0xa0, 0x42, 0xc3, 0x02, 0x00, 0x00,
}
