// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ids/ids.proto

package ids // import "github.com/airmap/interfaces/src/go/ids"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Operator models the unique id of an operator.
type Operator struct {
	AsString             string   `protobuf:"bytes,1,opt,name=as_string,json=asString,proto3" json:"as_string,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Operator) Reset()         { *m = Operator{} }
func (m *Operator) String() string { return proto.CompactTextString(m) }
func (*Operator) ProtoMessage()    {}
func (*Operator) Descriptor() ([]byte, []int) {
	return fileDescriptor_ids_fcd412f0d4da9d69, []int{0}
}
func (m *Operator) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Operator.Unmarshal(m, b)
}
func (m *Operator) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Operator.Marshal(b, m, deterministic)
}
func (dst *Operator) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Operator.Merge(dst, src)
}
func (m *Operator) XXX_Size() int {
	return xxx_messageInfo_Operator.Size(m)
}
func (m *Operator) XXX_DiscardUnknown() {
	xxx_messageInfo_Operator.DiscardUnknown(m)
}

var xxx_messageInfo_Operator proto.InternalMessageInfo

func (m *Operator) GetAsString() string {
	if m != nil {
		return m.AsString
	}
	return ""
}

// Operation models the unique id of an operation.
type Operation struct {
	AsString             string   `protobuf:"bytes,1,opt,name=as_string,json=asString,proto3" json:"as_string,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Operation) Reset()         { *m = Operation{} }
func (m *Operation) String() string { return proto.CompactTextString(m) }
func (*Operation) ProtoMessage()    {}
func (*Operation) Descriptor() ([]byte, []int) {
	return fileDescriptor_ids_fcd412f0d4da9d69, []int{1}
}
func (m *Operation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Operation.Unmarshal(m, b)
}
func (m *Operation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Operation.Marshal(b, m, deterministic)
}
func (dst *Operation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Operation.Merge(dst, src)
}
func (m *Operation) XXX_Size() int {
	return xxx_messageInfo_Operation.Size(m)
}
func (m *Operation) XXX_DiscardUnknown() {
	xxx_messageInfo_Operation.DiscardUnknown(m)
}

var xxx_messageInfo_Operation proto.InternalMessageInfo

func (m *Operation) GetAsString() string {
	if m != nil {
		return m.AsString
	}
	return ""
}

// USS models the unique id of a UTM Service Supplier (USS)
type USS struct {
	AsString             string   `protobuf:"bytes,1,opt,name=as_string,json=asString,proto3" json:"as_string,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *USS) Reset()         { *m = USS{} }
func (m *USS) String() string { return proto.CompactTextString(m) }
func (*USS) ProtoMessage()    {}
func (*USS) Descriptor() ([]byte, []int) {
	return fileDescriptor_ids_fcd412f0d4da9d69, []int{2}
}
func (m *USS) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_USS.Unmarshal(m, b)
}
func (m *USS) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_USS.Marshal(b, m, deterministic)
}
func (dst *USS) XXX_Merge(src proto.Message) {
	xxx_messageInfo_USS.Merge(dst, src)
}
func (m *USS) XXX_Size() int {
	return xxx_messageInfo_USS.Size(m)
}
func (m *USS) XXX_DiscardUnknown() {
	xxx_messageInfo_USS.DiscardUnknown(m)
}

var xxx_messageInfo_USS proto.InternalMessageInfo

func (m *USS) GetAsString() string {
	if m != nil {
		return m.AsString
	}
	return ""
}

func init() {
	proto.RegisterType((*Operator)(nil), "ids.Operator")
	proto.RegisterType((*Operation)(nil), "ids.Operation")
	proto.RegisterType((*USS)(nil), "ids.USS")
}

func init() { proto.RegisterFile("ids/ids.proto", fileDescriptor_ids_fcd412f0d4da9d69) }

var fileDescriptor_ids_fcd412f0d4da9d69 = []byte{
	// 148 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcd, 0x4c, 0x29, 0xd6,
	0xcf, 0x4c, 0x29, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xce, 0x4c, 0x29, 0x56, 0x52,
	0xe7, 0xe2, 0xf0, 0x2f, 0x48, 0x2d, 0x4a, 0x2c, 0xc9, 0x2f, 0x12, 0x92, 0xe6, 0xe2, 0x4c, 0x2c,
	0x8e, 0x2f, 0x2e, 0x29, 0xca, 0xcc, 0x4b, 0x97, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0xe2, 0x48,
	0x2c, 0x0e, 0x06, 0xf3, 0x95, 0x34, 0xb8, 0x38, 0x21, 0x0a, 0x33, 0xf3, 0xf3, 0xf0, 0xab, 0x54,
	0xe2, 0x62, 0x0e, 0x0d, 0x0e, 0xc6, 0xab, 0xc6, 0x49, 0x33, 0x4a, 0x3d, 0x3d, 0xb3, 0x24, 0xa3,
	0x34, 0x49, 0x2f, 0x39, 0x3f, 0x57, 0x3f, 0x31, 0xb3, 0x28, 0x37, 0xb1, 0x40, 0x3f, 0x33, 0xaf,
	0x24, 0xb5, 0x28, 0x2d, 0x31, 0x39, 0xb5, 0x58, 0xbf, 0xb8, 0x28, 0x59, 0x3f, 0x3d, 0x1f, 0xe4,
	0xd8, 0x24, 0x36, 0xb0, 0x6b, 0x8d, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0xf8, 0x0b, 0x36, 0x2b,
	0xbe, 0x00, 0x00, 0x00,
}
